# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    show-sql: true
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://192.168.99.100:6033/murali?useSSL=false
    username: root
    password: Platform@123
    driver-class-name: com.mysql.jdbc.Driver

jwt:
  header: Authorization
  secret: mySecret
  expiration: 120
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    org.springframework:
      security: DEBUG